version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    ports:
      - "3307:3306"


  app-tier:
    build: 
      context: ./application-code/app-tier
      dockerfile: Dockerfile
    container_name: app-tier
    ports:
      - "4000:4000"
    environment:    #Passes environment variables to backend app  to connect to the DB.
      DB_HOST: ${DB_HOST}
      DB_USER:  ${DB_USER}
      DB_PWD:  ${DB_PWD}
      DB_DATABASE:  ${DB_DATABASE}
    
    depends_on:
          - db

  web:
    build: 
      context: ./application-code/web-tier
      dockerfile: Dockerfile
    container_name: web-tier
    ports:
      - "3000:80"
    
    depends_on:
       - app-tier




# Add image: fields to each service so you can easily tag and push them later.


# services:
#   db:
#     image: $DOCKERHUB_USERNAME/tierhub_db:latest
#     container_name: db
#     ...

#   app-tier:
#     image: $DOCKERHUB_USERNAME/tierhub_app:latest
#     build:
#       context: ./application-code/app-tier
#       dockerfile: Dockerfile
#     container_name: app-tier
#     ...

#   web:
#     image: $DOCKERHUB_USERNAME/tierhub_frontend:latest
#     build:
#       context: ./application-code/web-tier
#       dockerfile: Dockerfile
#     container_name: web-tier
#     ...
# Then your GitHub Actions can simply push without needing to tag:


# - name: Push Docker Images
#   run: |
#     docker push $DOCKERHUB_USERNAME/tierhub_frontend:latest
#     docker push $DOCKERHUB_USERNAME/tierhub_app:latest
#     docker push $DOCKERHUB_USERNAME/tierhub_db:latest